# Generated by Django 5.1.6 on 2025-02-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudentApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
