# Generated by Django 5.1.6 on 2025-02-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("TaskApp", "0002_delete_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
