# Generated by Django 5.1.7 on 2025-03-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Customer", "Customer"),
                    ("Seller", "Seller"),
                    ("Admin", "Admin"),
                ],
                default="Customer",
                max_length=10,
            ),
        ),
    ]
